version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main
            deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
            apt-get update
            apt-get install clang-8 lldb-8 lld-8
      - run:
          name: Update environment
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
            cargo install chisel
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Build
          command: make
